name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - 29.1
        experimental: [false]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v3
    - name: Run tests
      run: emacs --batch -l ./init.el --eval '(message "Init file loaded successfully!")'
